[[redirects]]
  from = "/subscriptions"
  to = "https://abstergo-industries.herokuapp.com/subscriptions"
  status = 200
  force = true

    [[redirects]]
  from = "/applicants"
  to = "https://abstergo-industries.herokuapp.com/applicants"
  status = 200
  force = true